import { seal, unseal } from './mcp-oauth.js';
const ORG = '019e912f-6166-74e7-9bd1-398ac2eb4231';
const WORKSPACE = '019e912f-6193-7852-bd82-a991a82ff18f';
const ROOT = `https://apps.sarvam.ai/api/scheduling/v1/orgs/${ORG}/workspaces/${WORKSPACE}`;
const TEST = '+919537097267';
const now = () => Math.floor(Date.now()/1000);
async function key(env){const row=await env.CATALOG_DB.prepare('SELECT api_key FROM wa_operator_sarvam_rest WHERE id=1').first();return row?.api_key?unseal(row.api_key,env.AGENT_ADMIN_KEY):null;}
async function call(env,path,options={},fetchFn=fetch){const token=await key(env);if(!token)throw new Error('Connect Sarvam Voice Agents API first');const r=await fetchFn(ROOT+path,{...options,headers:{'X-API-Key':token,accept:'application/json','content-type':'application/json'}});const raw=await r.text();let data={};try{data=JSON.parse(raw)}catch{}if(!r.ok)throw new Error(r.status===401||r.status===403?'Sarvam API key rejected or lacks access':`Sarvam HTTP ${r.status}`);return data;}
export async function sarvamRestStatus(env){return {connected:Boolean(await key(env)),api:'Voice Agents REST',testRecipient:TEST};}
export async function saveSarvamRestKey(env,value,fetchFn=fetch){const token=String(value||'').trim();if(token.length<16||token.length>512||/\s/.test(token))throw new Error('Enter a valid Sarvam API key');await call(env,'/campaigns?limit=1',{method:'GET'},fetchFn).catch(e=>{if(!/HTTP 404/.test(e.message))throw e});await env.CATALOG_DB.prepare(`INSERT INTO wa_operator_sarvam_rest (id,api_key,updated_at) VALUES(1,?,?) ON CONFLICT(id) DO UPDATE SET api_key=excluded.api_key,updated_at=excluded.updated_at`).bind(await seal(token,env.AGENT_ADMIN_KEY),now()).run();return {connected:true};}
export async function listSarvamRestCampaigns(env,fetchFn=fetch){return call(env,'/campaigns?limit=25',{method:'GET'},fetchFn);}
export async function stageSarvamRest(env,sessionId,args){if(!/^[A-Za-z0-9_-]{8,80}$/.test(sessionId))throw new Error('Invalid operator session');const to='+'+String(args.to||'').replace(/\D/g,'');if(to!==TEST)throw new Error('The first campaign is limited to +91 95370 97267');const start=Date.parse(args.startAt||'');if(!Number.isFinite(start)||start<Date.now()+600000)throw new Error('Call time must be at least 10 minutes ahead');const id=crypto.randomUUID();const clean={to,purpose:String(args.purpose||'payment follow-up').slice(0,80),details:String(args.details||'').slice(0,600),startAt:new Date(start).toISOString()};await env.CATALOG_DB.prepare(`INSERT INTO wa_operator_sarvam_rest_actions(id,session_id,arguments_json,status,created_at,updated_at) VALUES(?,?,?,'pending',?,?)`).bind(id,sessionId,JSON.stringify(clean),now(),now()).run();return {id,...clean,status:'pending'};}
export async function pendingSarvamRest(env,sessionId){const {results}=await env.CATALOG_DB.prepare("SELECT id,arguments_json,status FROM wa_operator_sarvam_rest_actions WHERE session_id=? AND status IN ('pending','unknown') ORDER BY created_at DESC LIMIT 10").bind(sessionId).all();return results.map(r=>({id:r.id,...JSON.parse(r.arguments_json),status:r.status}));}
export async function confirmSarvamRest(env,id,fetchFn=fetch){const row=await env.CATALOG_DB.prepare("SELECT * FROM wa_operator_sarvam_rest_actions WHERE id=? AND status='pending'").bind(id).first();if(!row)throw new Error('Sarvam action unavailable');const a=JSON.parse(row.arguments_json);await env.CATALOG_DB.prepare("UPDATE wa_operator_sarvam_rest_actions SET status='running',updated_at=? WHERE id=?").bind(now(),id).run();try{const campaign=await call(env,'/campaigns',{method:'POST',body:JSON.stringify({name:`Chandni ${a.purpose} test`,description:a.details,app_config:{app_id:'chandni-bot-5263af98-35c0',app_type:'agent',app_version:7,attempts_per_second:1,connection_configs:[{connection_id:'10dff518-de-11d813aa-80e8',phone_numbers:['+917971170755'],weight:1}]},start_timestamp:a.startAt,end_timestamp:new Date(Date.parse(a.startAt)+3600000).toISOString(),allowed_schedule:{allowed_start_time:'09:00',allowed_end_time:'19:00',allowed_days:['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],timezone:'Asia/Kolkata'}})},fetchFn);await env.CATALOG_DB.prepare("UPDATE wa_operator_sarvam_rest_actions SET status='completed',result_json=?,updated_at=? WHERE id=?").bind(JSON.stringify(campaign).slice(0,6000),now(),id).run();return {status:'completed',campaign};}catch(e){await env.CATALOG_DB.prepare("UPDATE wa_operator_sarvam_rest_actions SET status='unknown',result_json=?,updated_at=? WHERE id=?").bind(JSON.stringify({error:String(e.message).slice(0,200)}),now(),id).run();throw e;}}
